### ISSUE TITLE
Thumb code

### ISSUE THREAD

**Issue by kynex7510** [devkitPro/3dstools#16]
I'm generating assembly files as part of the build process, which are then linked against standalone code to build homebrew. The generated code uses thumb instructions, however when building as a 3dsx it fails with  `Unaligned relocation!`. By [reading the tool code](https://github.com/devkitPro/3dstools/blob/master/src/3dsxtool.cpp#L131), I see it expects addresses aligned to 4 bytes, however my application has a R_ARM_THM_CALL relocation at an address aligned to 2 bytes. Moreover, this relocation doesn't appear anywhere within the tool code, so do I have to assume compiling thumb code is not supported?

**Comment by fincs** [comment]
We generally do not support Thumb mode on 3DS because Thumb-1 does not have a way to access VFP registers (Thumb-2 does, but the MPCore does not support it). The armv6k hardfloat ABI we use requires VFP registers, even when functions taking float arguments aren't used or implemented -- remember that variadic functions can take float arguments too, and that extends to how `va_list` works. Trying to compile C code as Thumb fails with a `sorry, unimplemented: Thumb-1 hard-float VFP ABI` error. Adding support for Thumb would entail needing to maintain softfloat builds of the entire set of 3DS homebrew libraries and portlibs, something that we do not believe to be worthwhile doing.

With that said, you seem to have (deliberately?) sidestepped these problems by avoiding C and instead using assembler, which does not have the concept of ABI. It would be helpful to describe in more detail what your project is, and why it needs Thumb mode functions. The error you're currently hitting stems from the fact that 3DSX relocations are not designed to be appliable at word misaligned locations; although I think in this case `R_ARM_THM_CALL` could be safely ignored since it doesn't need runtime processing.

**Comment by kynex7510** [comment]
Thanks for the clarification, I've chosen thumb mode simply because of the smaller code size footprint, but the code is small to begin with so ARM mode is not a problem. Just pedantry haha
