### ISSUE TITLE
Exceptions in 3dsx converted from ELF do not work as expected

### ISSUE THREAD

**Issue by Xtansia** [devkitPro/3dstools#5]
I'm converting an ELF binary using exceptions to a 3dsx using 3dsxtool.
When running the ELF directly in Citra exhibits the correct behavior of the exception being caught,
but when running the generated 3dsx in Citra it crashes when the exception is thrown.
I'm using devkitARM r46 on Linux.

[Test case](https://gist.github.com/Xtansia/6683f35c89fbf7c90a640d1664f4b50f).

**Comment by fincs** [comment]
Thank you for your test case.

After some investigation, it looks like the problem resides in Citra's 3dsx loader code, and not 3dsxtool. Turns out Citra [does not yet support](https://github.com/citra-emu/citra/blob/master/src/core/loader/3dsx.cpp#L185) the special relocation types [added two years ago](https://github.com/devkitPro/3dstools/commit/47bea18f5cded3437552e3af968aa1356e2d6f3e#diff-8bc872c01cd7836116ee2424e204e9c9R124) in order to properly support C++ exceptions. The generated binary, of course, works perfectly on real hardware (with hax payload 2.8).

I'd suggest to create an issue in the Citra repository, to notify its developers of this shortcoming.

**Comment by Xtansia** [comment]
Ah I see, thank you, I should have tried it on real hardware but didn't have my 3DS at hand at the time.
